In [2]:
#1 
for i in range(1500,2700):
    if (i%7==0 and i%5==0):
        print(i,end=" ")

1505 1540 1575 1610 1645 1680 1715 1750 1785 1820 1855 1890 1925 1960 1995 2030 2065 2100 2135 2170 2205 2240 2275 2310 2345 2380 2415 2450 2485 2520 2555 2590 2625 2660 2695 

In [1]:
n=int(input('Enter a Number :'))
for i in range(1,11):
    print(n,'*',i,'=',n*i)

Enter a Number :6
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60


In [9]:
# 2 
c=60
fah=c*1.8+32
print(c,'Celsius is ',fah,'in Fahrenheit')
fah=45
c=fah*.5556-(32)
print(fah,'Fahrenhite is ',round( c,1),'in Celsius')


60 Celsius is  140.0 in Fahrenheit
45 Fahrenhite is  -7.0 in Celsius


In [1]:
v=input("Enter F/C:")
C=float(input("Enter the temperature:" ))
if v=="C":
    f=(C*1.8)+32
    print(C,"celcius is",f,"in Fahrenheit")
else:
    c=(C-32)/1.8
    print(C,"fehrenheit is",c,"in Celsius")

Enter F/C:60
Enter the temperature:45
45.0 fehrenheit is 7.222222222222222 in Celsius


In [1]:
import random
# library that we use in order to choose
# on random words from a list of words
 
name = input("What is your name? ")
# Here the user is asked to enter the name first
 
print("Good Luck ! ", name)
 
words = ['rainbow', 'computer', 'science', 'programming',
         'python', 'mathematics', 'player', 'condition',
         'reverse', 'water', 'board', 'geeks']
 
# Function will choose one random
# word from this list of words
word = random.choice(words)
 
 
print("Guess the characters")
 
guesses = ''
 
# any number of turns can be used here
turns = 12
 
 
while turns > 0:
     
    # counts the number of times a user fails
    failed = 0
     
    # all characters from the input
    # word taking one at a time.
    for char in word:
         
        # comparing that character with
        # the character in guesses
        if char in guesses:
            print(char, end=" ")
             
        else:
            print("_")
            print(char, end=" ")
             
            # for every failure 1 will be
            # incremented in failure
            failed += 1
             
 
    if failed == 0:
        # user will win the game if failure is 0
        # and 'You Win' will be given as output
        print("You Win")
         
        # this print the correct word
        print("The word is: ", word)
        break
     
    # if user has input the wrong alphabet then
    # it will ask user to enter another alphabet
    print()
    guess = input("guess a character:")
     
    # every input character will be stored in guesses
    guesses += guess
     
    # check input with the character in word
    if guess not in word:
         
        turns -= 1
         
        # if the character doesn’t match the word
        # then “Wrong” will be given as output
        print("Wrong")
         
        # this will print the number of
        # turns left for the user
        print("You have", + turns, 'more guesses')
         
         
        if turns == 0:
            print("You Loose")

What is your name? a
Good Luck !  a
Guess the characters
_
p _
l _
a _
y _
e _
r 
guess a character:p
p _
l _
a _
y _
e _
r 
guess a character:l
p l _
a _
y _
e _
r 
guess a character:a
p l a _
y _
e _
r 
guess a character:y
p l a y _
e _
r 
guess a character:e
p l a y e _
r 
guess a character:r
p l a y e r You Win
The word is:  player


In [4]:
# 2
import random


x =random.randint(1,10)
print(x) 
count = 0 
while count < 3:
    count += 1
    guess = int(input("Guess a number:- "))
    if x == guess:
        print("Congratulations Well done ",
              count, " try")
        break
    elif x < guess:
        print("appear again")
# shows this output.
if count >= 3:
    print("\nThe number is %d" % x)
    print("\tBetter Luck Next time!")
 

    


3
Guess a number:- 8
appear again
Guess a number:- 3
Congratulations Well done  2  try


In [ ]:
while True:
    import random as r
    n=int(input("Enter the guess number: "))
    r=r.randint(1,9)
    if n==r:
        print("Well guessed!")
        break
    else:
        print("Try again")
        continue

Enter the guess number: 8
Try again
Enter the guess number: 1
Try again


In [12]:
# 4
n=int(input('Enter a Number :'))
for i in range(1,n+1):
    print('* '*i)
for i in range(n-1,0,-1):
    print('* '*i)

Enter a Number :7
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * * * 
* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [1]:
for i in range(1,6):
    print('* '*i)
for j in range(4,0,-1):
    print('* '*j)

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [6]:
a=input('Enter a Word :-')
print(a[::-1])  # Reverse String

Enter a Word :-Anil Tiwari
irawiT linA


In [2]:
def reverse (string):
    r_str=""
    for i in string:
        r_str=i+r_str
    print('reversed string :',r_str)
    
string=input('Enter a string :')

reverse(string)

Enter a string :Anil TIWARI is great all rounder
reversed string : rednuor lla taerg si IRAWIT linA


In [2]:
# 6
even_count=0
odd_count=0
list=[1,2,3,4,5,6,7,8,9]
for number in list:
    if number%2==0:
        print(number,'Even Number ')
        even_count=even_count+1
    else:
        print(number,'Odd Number ')
        odd_count=odd_count+1        
print('Count of Even Number :',even_count)
print('Count of Odd Number  :',odd_count)
        
            

1 Odd Number 
2 Even Number 
3 Odd Number 
4 Even Number 
5 Odd Number 
6 Even Number 
7 Odd Number 
8 Even Number 
9 Odd Number 
Count of Even Number : 4
Count of Odd Number  : 5


In [2]:
o=0
e=0
for i in range(1,10):
    if i%2==0:
        e=e+1
    else:
        o=o+1
        continue
print("Number of even numbers:",e)
print("Number of odd numbers:",o)

Number of even numbers: 4
Number of odd numbers: 5


In [4]:
#7
num=[1452,11.23,1+2j,True,'Python foundation',(0,-1),[5,12],{'class':'V','Section':'A'}]
for i in num:
    print(i,"------>",type(i))

1452 ------> <class 'int'>
11.23 ------> <class 'float'>
(1+2j) ------> <class 'complex'>
True ------> <class 'bool'>
Python foundation ------> <class 'str'>
(0, -1) ------> <class 'tuple'>
[5, 12] ------> <class 'list'>
{'class': 'V', 'Section': 'A'} ------> <class 'dict'>


In [18]:
#8
for i in range(1,7):
    if(i%3==0):  # 3,6
        continue
        print(i)
    else:
        print(i)        

1
2
4
5


In [2]:
def fib(n):
    if n==0 or n==1:
        return n
    else:
        return fib(n-1) + fib(n-2)
    

In [3]:
for i in range(0,5):
    print(f'Fib{i} is {fib(i)}')

Fib0 is 0
Fib1 is 1
Fib2 is 1
Fib3 is 2
Fib4 is 3


In [2]:
n = int(input('Enter a Number'))
a=0
b=1
for i in range(n):
    print(a)
    c=a
    a=b
    b=c+b

Enter a Number50
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049


In [5]:
x=0
y=1
z=1
while z<=50:
    print(x,z,end=" ")
    x=y
    y=z
    z=x+y

0 1 1 2 1 3 2 5 3 8 5 13 8 21 13 34 

In [7]:
# 10
for num in range (1,50):
    if num %3==0 and num%5==0:
        print('FizzBuzz')
    elif num %3==0:
        print('Fizz')
    elif num%5==0:
        print('Buzz')
    else:
        print(num)
    
        

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49


In [8]:
import numpy as np
b = np.array([[0,0,0,0],[0,1,2,3],[0,2,4,6]])
print(b)

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


In [6]:
n=int(input("Enter the number of rows:"))
m=int(input("Enter the number of columns:"))
for i in range(0,n):
    for j in range(0,m):
        if i==0 or j==0:
            print(0,end=" ")
        elif i==1:
            print(j,end=" ")
        else:
            print(j*2,end=" ")
    print()

Enter the number of rows:3
Enter the number of columns:4
0 0 0 0 
0 1 2 3 
0 2 4 6 


SyntaxError: invalid syntax (Temp/ipykernel_13980/1033837251.py, line 3)